version: "3"

networks:
  default:
    driver: bridge

services:
  gitea:
    image: mpuchawski/gitea:latest
    container_name: gitea
    env_file:
      - config/gitea/.env
    volumes:
      - ./containers/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
      - keycloak
    extra_hosts:
      - "$DOMAIN_NAME:$HOST_IP"
  jenkins:
    image: mpuchawski/jenkins:latest
    user: $CI_UID:$CI_GID
    ports:
      - 50000:50000
    container_name: jenkins
    depends_on:
      - keycloak
    group_add:
      - $DOCKER_GID
    environment:
      - DOCKER_GID
    env_file:
      - config/jenkins/.env
    volumes:
      - ./containers/jenkins:/var/jenkins_home
      - ./config/jenkins/casc.yaml:/usr/casc.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "$DOMAIN_NAME:$HOST_IP"
  proxy:
    image: mpuchawski/proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/proxy/certs:/etc/ssl
      - ./config/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gitea
      - jenkins
      - keycloak
    extra_hosts:
      - "$DOMAIN_NAME:$HOST_IP"
  postgres:
    image: postgres:14.1-alpine
    env_file:
      - config/postgres/.env
    volumes:
      - ./containers/postgres:/var/lib/postgresql/data
      - ./config/postgres/init-sql.sh:/docker-entrypoint-initdb.d/init-sql.sh
    extra_hosts:
      - "$DOMAIN_NAME:$HOST_IP"
    ports:
      - "5432:5432"
  keycloak:
    image: mpuchawski/keycloak:latest
    env_file:
      - config/keycloak/.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/keycloak" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./config/keycloak/import:/opt/keycloak/data/import:ro
    extra_hosts:
      - "$DOMAIN_NAME:$HOST_IP"
    depends_on:
      - postgres