jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "GROUP:Job/Build:read"
      - "GROUP:Job/Cancel:read"
      - "GROUP:Job/Read:read"
      - "GROUP:Job/Workspace:read"
      - "GROUP:Overall/Administer:modify"
      - "GROUP:Overall/Read:read"
      - "GROUP:Run/Delete:read"
      - "GROUP:Run/Replay:read"
      - "GROUP:Run/Update:read"
      - "GROUP:View/Configure:read"
      - "GROUP:View/Read:read"
  clouds:
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "unix:///var/run/docker.sock"
        readTimeout: 60
      name: "docker"
      templates:
      - connector:
          jnlp:
            jenkinsUrl: "http://jenkins:8080/jenkins"
            jnlpLauncher:
              workDirSettings:
                disabled: false
                failIfWorkDirIsMissing: false
                internalDir: "remoting"
            user: "jenkins"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          extraGroups:
            - "998"
          extraGroupsString: "998"
          image: "mpuchawski/agent-builder:latest"
          network: "ci-cd-network"
          mounts:
            - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
          mountsString: "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
        labelString: "agent-builder"
        mode: EXCLUSIVE
        name: "agent-builder"
        pullTimeout: 300
        remoteFs: "/home/jenkins"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.diagnostics.ControllerExecutorsNoAgents"
  labelAtoms:
  - name: "built-in"
  - name: "cloud"
  - name: "local"
  labelString: "local"
  markupFormatter: "plainText"
  mode: EXCLUSIVE
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    oic:
      authorizationServerUrl: "https://${DOMAIN_NAME}/keycloak/realms/ci_cd/protocol/openid-connect/auth"
      clientId: "jenkins"
      clientSecret: "${JENKINS_CLIENT_SECRET}"
      disableSslVerification: true
      endSessionEndpoint: "https://${DOMAIN_NAME}/keycloak/realms/ci_cd/protocol/openid-connect/logout"
      escapeHatchEnabled: false
      escapeHatchSecret: "{AQAAABAAAAAQculWkCqzJ3On/E1Y5f04g7YhVpLh3DRrVcOUi2P1It0=}"
      groupsFieldName: "groups"
      logoutFromOpenidProvider: true
      postLogoutRedirectUrl: "https://${DOMAIN_NAME}/jenkins"
      scopes: "openid microprofile-jwt offline_access address acr email profile roles\
        \ web-origins phone group-membership"
      tokenAuthMethod: "client_secret_basic"
      tokenServerUrl: "https://${DOMAIN_NAME}/keycloak/realms/ci_cd/protocol/openid-connect/token"
      userInfoServerUrl: "https://${DOMAIN_NAME}/keycloak/realms/ci_cd/protocol/openid-connect/userinfo"
      userNameField: "preferred_username"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  giteaServers:
    servers:
    - displayName: "gitea-server"
      manageHooks: false
      serverUrl: "http://gitea:3000"
  location:
    adminAddress: "N/A"
    url: "https://${DOMAIN_NAME}/jenkins/"
  junitTestResultStorage:
    storage: "file"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"

 
