jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "GROUP:Job/Build:read"
      - "GROUP:Job/Cancel:read"
      - "GROUP:Job/Read:read"
      - "GROUP:Job/Workspace:read"
      - "GROUP:Overall/Administer:modify"
      - "GROUP:Overall/Read:read"
      - "GROUP:Run/Delete:read"
      - "GROUP:Run/Replay:read"
      - "GROUP:Run/Update:read"
      - "GROUP:View/Configure:read"
      - "GROUP:View/Read:read"
  clouds:
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "unix:///var/run/docker.sock"
        readTimeout: 60
      name: "docker"
      templates:
      - connector:
          jnlp:
            jnlpLauncher:
              workDirSettings:
                disabled: false
                failIfWorkDirIsMissing: false
                internalDir: "remoting"
            user: "jenkins"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          extraGroups:
          - "^${DOCKER_GROUP}"
          extraGroupsString: "^${DOCKER_GROUP}"
          image: "mpuchawski/cloud-slave:latest"
          mounts:
          - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
          mountsString: "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
        labelString: "cloud"
        mode: EXCLUSIVE
        name: "cloud"
        pullTimeout: 300
        remoteFs: "/home/jenkins"
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java8-slave:latest"
        labelString: "java8"
        mode: EXCLUSIVE
        name: "java8"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/javascript-slave:latest"
        labelString: "javascript"
        mode: EXCLUSIVE
        name: "javascript"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java9-slave:latest"
        labelString: "java9"
        mode: EXCLUSIVE
        name: "java9"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java11-slave:latest"
        labelString: "java11"
        mode: EXCLUSIVE
        name: "java11"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/javascript-chromium-slave:latest"
        labelString: "javascript-chromium"
        mode: EXCLUSIVE
        name: "javascript-chromium"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java10-slave:latest"
        labelString: "java10"
        mode: EXCLUSIVE
        name: "java10"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java12-slave:latest"
        labelString: "java12"
        mode: EXCLUSIVE
        name: "java12"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java13-slave:latest"
        labelString: "java13"
        mode: EXCLUSIVE
        name: "java13"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java14-slave:latest"
        labelString: "java14"
        mode: EXCLUSIVE
        name: "java14"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java15-slave:latest"
        labelString: "java15"
        mode: EXCLUSIVE
        name: "java15"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java16-slave:latest"
        labelString: "java16"
        mode: EXCLUSIVE
        name: "java16"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java13-with-libreoffice-slave:latest"
        labelString: "java13-with-libreoffice"
        mode: EXCLUSIVE
        name: "java13-with-libreoffice"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java15-with-libreoffice-slave:latest"
        labelString: "java15-with-libreoffice"
        mode: EXCLUSIVE
        name: "java15-with-libreoffice"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java17-slave:latest"
        labelString: "java17"
        mode: EXCLUSIVE
        name: "java17"
        pullTimeout: 300
      - connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "jfactory/java16-browsers-slave:latest"
        labelString: "java16-browsers"
        mode: EXCLUSIVE
        name: "java16-browsers"
        pullTimeout: 300
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.diagnostics.ControllerExecutorsNoAgents"
  labelAtoms:
  - name: "built-in"
  - name: "cloud"
  - name: "java10"
  - name: "java11"
  - name: "java12"
  - name: "java13"
  - name: "java13-with-libreoffice"
  - name: "java14"
  - name: "java15"
  - name: "java15-with-libreoffice"
  - name: "java16"
  - name: "java16-browsers"
  - name: "java17"
  - name: "java8"
  - name: "java9"
  - name: "javascript"
  - name: "javascript-chromium"
  - name: "local"
  labelString: "local"
  markupFormatter: "plainText"
  mode: EXCLUSIVE
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    oic:
      authorizationServerUrl: "https://${DOMAIN_NAME}/keycloak/realms/ci_cd/protocol/openid-connect/auth"
      clientId: "jenkins"
      clientSecret: "${JENKINS_CLIENT_SECRET}"
      disableSslVerification: true
      endSessionEndpoint: "https://${DOMAIN_NAME}/keycloak/realms/ci_cd/protocol/openid-connect/logout"
      escapeHatchEnabled: false
      escapeHatchSecret: "{AQAAABAAAAAQculWkCqzJ3On/E1Y5f04g7YhVpLh3DRrVcOUi2P1It0=}"
      groupsFieldName: "groups"
      logoutFromOpenidProvider: true
      postLogoutRedirectUrl: "https://${DOMAIN_NAME}/jenkins"
      scopes: "openid microprofile-jwt offline_access address acr email profile roles\
        \ web-origins phone group-membership"
      tokenAuthMethod: "client_secret_basic"
      tokenServerUrl: "https://${DOMAIN_NAME}/keycloak/realms/ci_cd/protocol/openid-connect/token"
      userInfoServerUrl: "https://${DOMAIN_NAME}/keycloak/realms/ci_cd/protocol/openid-connect/userinfo"
      userNameField: "preferred_username"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  giteaServers:
    servers:
    - displayName: "gitea-server"
      manageHooks: false
      serverUrl: "https://${DOMAIN_NAME}/gitea"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "https://${DOMAIN_NAME}/jenkins/"
  junitTestResultStorage:
    storage: "file"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"

 
